version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ecom-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ecom_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./ecom-backend
    container_name: ecom-backend-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecom_db?allowPublicKeyRetrieval=TRUE&useSSL=FALSE
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./myshop-frontend
    container_name: ecom-frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: